### ISSUE TITLE
Make the test-suite fly

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#100]
Not high priority, but it would be nice to find ways to make the test-suite take less time to complete. Tests should run as fast as possible and tests which use `sleep` to wait for certain tasks may be refactored to complete as fast as possible.

**Comment by thasmo** [comment]
Maybe it would benefit us by using an existing testing framework. A quick search revealed [bats](https://github.com/bats-core/bats-core/) and [shunit2](https://github.com/kward/shunit2).

**Comment by thasmo** [comment]
`bats` looks really nice, I think. I've added some test-case examples which can be run with `bats`.
https://github.com/dst-academy/docker-dontstarvetogether/tree/feature/test-suite-rewrite/tests

Opinions?

**Comment by BraisGabin** [comment]
I like it. We defenetly need a framework to run the tests. I created my own because I didn't find any.
