### ISSUE TITLE
How to update game files?

### ISSUE THREAD

**Issue by victoryancn** [yeet-zone/docker-dontstarvetogether#101]
Server shows up "this server is on an older version than you and cannot connect";

**Comment by victoryancn** [comment]
Server shows up "this server is on an older version than you and cannot connect";

**Comment by BraisGabin** [comment]
How do you launch the game container? Do you have the `--update=game` or `--update=all` flags

**Comment by thasmo** [comment]
We should probably document it better.

**Comment by BraisGabin** [comment]
Yep, probably. But we must be sure that the image on docker hub is the newest version too. So we can just say: `docker-compose pull`.

**Comment by thasmo** [comment]
Feel free to reply if you have further questions regarding this.
