### ISSUE TITLE
Some questions~

### ISSUE THREAD

**Issue by JemiloII** [yeet-zone/docker-dontstarvetogether#102]
So env files are nice, but how can I omit some of them? I would rather just -v /configs or something and have my mod files raw. I want to handle most of the workload with files instead of env variables. I don't want to over pollute the global namespace.

Also how can I use a volume of my own for the game data? I like to be able to keep my data in the event the container becomes corrupt or something.

If you're curious, I am building an electron manager and I enjoy using docker containers to keep everything bundled nicely, however, to make it easier to manage and more maintainable, I need to split some. Originally I was looking up another docker container I've used in the past, however, you guys seem to have a lot going on. I'm willing to give what you guys have a go.

**Comment by BraisGabin** [comment]
> So env files are nice, but how can I omit some of them? I would rather just -v /configs or something and have my mod files raw. I want to handle most of the workload with files instead of env variables. I don't want to over pollute the global namespace.

I didn't check it yet, but I think that you can use `-v` for each file you want to override. But this is a good feature request.

> Also how can I use a volume of my own for the game data? I like to be able to keep my data in the event the container becomes corrupt or something.

Right now you can do this all the game data is stored in a volume.

**Comment by thasmo** [comment]
> So env files are nice, but how can I omit some of them? I would rather just -v /configs or something and have my mod files raw.

I think you should be able to mount any file and/or directory easily via Docker volumes, although I've never checked to run/start a container without providing any env-variables.

> Also how can I use a volume of my own for the game data?

Simply mount the config directory using Docker volumes. By default, I think, the config directory is mounted as a volume anyway, it just uses the Docker-native volumes directory instead of a custom path.

**Comment by JemiloII** [comment]
i'll give that a try thanks again.
