### ISSUE TITLE
Port 10999 still exposed by dockerfile even when SERVER_PORT set

### ISSUE THREAD

**Issue by oshotton** [yeet-zone/docker-dontstarvetogether#103]
I set the environment variable SERVER_PORT in the docker-compose file to 10232 but port 10999 is still exposed. See screenshot:
![image](https://user-images.githubusercontent.com/5147961/29218204-ec1d9584-7eab-11e7-998c-c54f83cecc68.png)

I'm no docker expert but I think this is because environment variables aren't available at build time so when the port is exposed on [line 74 of the Dockerfile](https://github.com/dst-academy/docker-dontstarvetogether/blob/develop/build/Dockerfile#L73) it's still using the SERVER_PORT value of 10999 as set on [line 18](https://github.com/dst-academy/docker-dontstarvetogether/blob/develop/build/Dockerfile#L18).

Shouldn't the port not be exposed inside the Dockerfile and just be left for the user to set up in the ports section of the compose file?

**Comment by thasmo** [comment]
One underlying problem occurs when running a multi-world/container setup. Normally an application running inside a container should run fine when using the application's default port, 10999 in the case of DST. So, when running two worlds which are connected to each other, I'd usually want to run two containers, which run both on 10999 internally and I'd expose 10999->10999 on the first container and 10999->11000 on the second container, to the public. Unfortunately this does not work for reasons we don't know. This is why it's possible to actually configure/change the internal port via an environment variable and run something like 10999->10999 and 11000->11000.

It's probably true that binding the environment variable dynamically (at build time) in the Dockerfile won't work but I haven't tested this thoroughly. 

On the screenshot you posted, the underlined port number (in red) is the internally exposed port (on the Docker network).

Do you believe the port should not be exposed internally by Docker if a different one is defined explicitely? I'm not sure it would just expose it anyway. But maybe I'm totally wrong.

**Comment by BraisGabin** [comment]
> Unfortunately this does not work for reasons we don't know. This is why it's possible to actually configure/change the internal port via an environment variable and run something like 10999->10999 and 11000->11000.

This should be filled as bug at Klei's forum... Or maybe we did it before. 

In the oder hand... Probably we can remove the port command from our Dockerfile exactly for this reason. The user should set it manually anyway.

**Comment by oshotton** [comment]
> I'd usually want to run two containers, which run both on 10999 internally and I'd expose 10999->10999 on the first container and 10999->11000 on the second container, to the public. Unfortunately this does not work for reasons we don't know.

So I actually had the same idea as you - on the master overworld server I kept the default internal port of 10999 and change the external port it was exposed to to 10232 (10999->10232). I noticed that I was able to connect to the server if I used the `c_connect(ip, port, password)` command but not if manually browsing to the server - I could see the server but clicking on it didn't allow me to connect. (Mind you I didn't test this at all so it could of also been some other artifact causing this issue)

> It's probably true that binding the environment variable dynamically (at build time) in the Dockerfile won't work but I haven't tested this thoroughly.

I thought this wasn't possible in docker? I thought environment variables were only available with the run command and not the build command. Maybe you could do it with build args though? I'm really just firing in the dark here though as never built a docker image before!

> Do you believe the port should not be exposed internally by Docker if a different one is defined explicitely? I'm not sure it would just expose it anyway. But maybe I'm totally wrong.

Yes, I don't think the Dockerfile should expose the port internally - especially if it's then not going to use it. I don't see how the Dockerfile will know whether or not to expose a port or be able to dynamically set which port is exposed as that information is passed as an environment variable to the run command and not to the build command which runs the Dockerfile.

> In the oder hand... Probably we can remove the port command from our Dockerfile exactly for this reason. The user should set it manually anyway.

Yeah I feel that if the user is going to be setting this anyway there is no reason to keep it there - especially if it is doing unnecessary things in cases where you specify your own server port.

**Comment by BraisGabin** [comment]
https://docs.docker.com/engine/reference/builder/#expose

`EXPOSE` is only informative. It really doesn't harm but it doesn't do any good. And as far as we know that this value must be set a lot of times expose the default value is useless.

**Comment by thasmo** [comment]
There's more information on the `docker run` [documentation](https://docs.docker.com/engine/reference/run/#expose-incoming-ports). `EXPOSE` defines the initial ports of the services running in the container. This means that in the best case, someone could run `docker run -P dstacademy/dontstarvetogether` and Docker will then use the internal ports (defined by `EXPOSE`) and bind them to random ports on the host.

This requires that the container's internal ports do not change, but - as we already figured out - we need to change them because otherwise multiple linked worlds will not work.

So, yes, I guess setting ports via the `EXPOSE` directive does not make sense here.

It would be so nice to pinpoint the problem and find a solution together with Klei, but I doubt they have the time to listen/work on this.

Maybe there's a way to get this running with the proper port-configuration but testing is quite time-consuming and odds are that it will not work whatever we try.

**Comment by thasmo** [comment]
The actual problem is, that if running two DST servers on a single machine, they both need a separate public port because they communicate via those public ports somehow and also the game clients use them to connect to the worlds/instances. Unfortunately it's not possible to teach the game-server that it has an internal and a different external port, I guess.

**Comment by BraisGabin** [comment]
I created a PR to fix this problem.

We, probably, must write the ports issue in a wiki page. How klei mess up private ports and internal ports. I think that we understand know the issue well enought to explain it and it can be helpfull to future issues.

**Comment by thasmo** [comment]
A developer from Klei gave me a vague hint that there are two CLI arguments for the nullrenderer executable, `-port` and `-external_port`.

> This is in the shipped version of the game I believe. If external_port is set, it will use that whenever something needs the port to connect to from an external pov. If it's not set then it uses the default behaviour which is to use port for both internal and external. 

Not sure this solves anything for us?!

**Comment by BraisGabin** [comment]
Hmmm... it seems promissing. Do you have a link? Did he write that on the Klei forum?

**Comment by thasmo** [comment]
He wrote me via direct message on the forums.

**Comment by BraisGabin** [comment]
Ok.

So... How can we know the container's open external ports? I think that we have more less the same problem.

**Comment by thasmo** [comment]
That's what I meant; not sure this helps us. :D
