### ISSUE TITLE
Mods not installed

### ISSUE THREAD

**Issue by JoffreyPoreeCoding** [yeet-zone/docker-dontstarvetogether#107]
Hi,

I use your DST server container, and it's very nice to work with it.

I saw a problem when add mods to the server and add mods_ovverides too. Mods are not installed/updated when container is created and also when I run 'dst-server update'.

I have to remove the mods overrides file and run mods.sh (or restart the container) to install mods.

I saw some fix on develop branch and maybe they will fix this bug.

**Comment by thasmo** [comment]
Did you start the container with the [`update`](https://github.com/dst-academy/server-play/blob/a960f21c48b8081f8d07ea6c2e4ca3ef25f59b68/configuration/docker-compose.yml#L5) option?

Issue #95 is not resolved yet, but when you restart the container, mods should get updated if you use the `update` option mentioned before.

**Comment by JoffreyPoreeCoding** [comment]
Attach to request #95

**Comment by JoffreyPoreeCoding** [comment]
How can I use update option on start?

EDIT: I found!

**Comment by thasmo** [comment]
Awesome! :)

**Comment by JoffreyPoreeCoding** [comment]
FYI : I made a create like that :

```
mods=`cat modlist.txt`
mods_overrides=`cat modoverrides.lua`

docker create --name dst_cave_slave \
    -p 11000:11000/udp \
    --env-file=".env" \
    -e MODS="$mods" \
    -e MODS_OVERRIDES="$mods_overrides" \
    -v /home/docker/datas/dst_cave_slave:/var/lib/dsta/cluster \
    dstacademy/dontstarvetogether \
    --update=all
```
