### ISSUE TITLE
Remove `WORLD_PRESET` logic

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#109]
Logic in `world.sh` which handles the `WORLD_PRESET` is not working at the moment and besides that it's quite problematic anyway. I'm in favor of removing it completely and give the responsibility of server-configuration via `LEVELDATA_OVERRIDES` to the server-admin.

**Comment by BraisGabin** [comment]
I imagine that `leveldataoverride.lua` is generated automatically with default values by the game if we don't set it. Am I right?

I think that we can simplify our WORD_PRESET (probably call it in a different way). A env variable that you can set as `FOREST` or `CAVE` and it just set the default values for a default forest or a default cave.

This implementation would be really easy: we have two static files in our image and we copy the correct one to `leveldataoverride.lua`.

But, can we found a "default `leveldataoverride.lua` forest" and a "default `leveldataoverride.lua` cave"?

**Comment by thasmo** [comment]
> But, can we found a "default leveldataoverride.lua forest" and a "default leveldataoverride.lua cave"?

That's the tricky part. I'd like to have the minimum default configurations, but as it's not documented it's quite some work to determine what' needed and what not. Also, every time Klei changes the file format, we have to adjust it. It would be a nice feature but in my oppinion the work we would have to put into it is not worth it.

**Comment by thasmo** [comment]
That's the "default" configuration for `DST_CAVE` which is generated when creating a server in the game.
```
return {
  background_node_range={ 0, 1 },
  desc="Delve into the caves... together!",
  hideminimap=false,
  id="DST_CAVE",
  location="cave",
  max_playlist_position=999,
  min_playlist_position=0,
  name="The Caves",
  numrandom_set_pieces=0,
  override_level_string=false,
  overrides={
    banana="default",
    bats="default",
    berrybush="default",
    boons="default",
    branching="default",
    bunnymen="default",
    cave_ponds="default",
    cave_spiders="default",
    cavelight="default",
    chess="default",
    disease_delay="default",
    earthquakes="default",
    fern="default",
    fissure="default",
    flint="default",
    flower_cave="default",
    grass="default",
    layout_mode="RestrictNodesByKey",
    lichen="default",
    liefs="default",
    loop="default",
    marshbush="default",
    monkey="default",
    mushroom="default",
    mushtree="default",
    petrification="default",
    prefabswaps_start="default",
    reeds="default",
    regrowth="default",
    roads="never",
    rock="default",
    rocky="default",
    sapling="default",
    season_start="default",
    slurper="default",
    slurtles="default",
    start_location="caves",
    task_set="cave_default",
    tentacles="default",
    touchstone="default",
    trees="default",
    weather="default",
    world_size="default",
    wormattacks="default",
    wormhole_prefab="tentacle_pillar",
    wormlights="default",
    worms="default" 
  },
  required_prefabs={ "multiplayer_portal" },
  substitutes={  },
  version=3 
}
```
I've spent quite some time to remove as much as possible but many values are mandatory including `name` and `desc`, and `overrides.task_set` etc. I guess it's doable, but as mentioned, it' some initial work and also some work to maintain it over time.

**Comment by BraisGabin** [comment]
Agree.

So what do you think  about removing all about `WORLD_PRESET` but create a new issue (without milestone) about this *new* and simplified feature? Maybe someone wants to investigate about this and founds an easy way to implement it. Both agree that this is a nice to have.

**Comment by thasmo** [comment]
Sounds good!

**Comment by thasmo** [comment]
Being handled in #111.
