### ISSUE TITLE
Split this image in 3

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#11]
The 3 images are:
- Steamcmd
- DST
- DST:A
##### Steamcmd Image
- Install steam dependencies
- Download the steamcmd
- Launch the steamcmd just to download all the team related files
- Add steamcmd.sh to the `PATH` (just for convenience)
##### DST Image
- Use steamcmd for download the game
- It would be great to add the `dontstarve_dedicated_server_nullrenderer` to the `PATH` but it use relative paths...
- scripts to update the game
##### DST:A Image
- Install dependencies (like ca-certificates)
- Install gosu
- Create user
- Open port
- create volume
- changue workdir
- entrypoint

**Comment by thasmo** [comment]
If we break this down to the basic steps, I'd say this is it:
- Install Steam
- Install DST
- Run DST

I think if these would be our 3 images, most of them need `gosu` to run the relevant executables as a specific user. This means we need to install `gosu` in the `steamcmd` image already.

To be honest, at the moment I don't see any real benefits by splitting this into 3 independent images, besides having ... 3 images. :D

If we would re-use any of those images, it makes sense, but for now, I don't see why we would need a separate `steamcmd` image.

This makes things way more complicated, I believe.

Please keep discussing! Maybe I'm overseeing something here or things get clearer the more information and requirements we know.

**Comment by BraisGabin** [comment]
Right now I think that, if we split this image, it must be only 2 images: Steam and DST. Anyway, I think that create a Steam image is outside the dst-academy scope.
