### ISSUE TITLE
Check and update example configurations

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#110]
Some of the examples don't work anymore, because I believe some mandatory options have been added to the `leveldataoverride.lua` which we do not set at the moment. That means, basically all examples using a `leveldataoverride.lua` possibly do not work anymore at the moment.

**Comment by CaptEmulation** [comment]
Fixed the shard example with https://github.com/dst-academy/docker-dontstarvetogether/pull/116
