### ISSUE TITLE
Improper handling of directories if shard name contains spaces

### ISSUE THREAD

**Issue by DrMurx** [yeet-zone/docker-dontstarvetogether#114]
I've tried to create a shard with a space character in it. Apparently, this confuses some part of the configuration shell scripts.

For example a shard name of "Cave 1" will result in 3 folders in the container:

* `/var/lib/dsta/Cave 1`
* `/var/lib/dsta/Cave`
* `/1`

**Comment by BraisGabin** [comment]
Thanks for the issue! This bug is fixed in the development branch and it'll be released in `v0.8`.
