### ISSUE TITLE
Implement a custom logger

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#12]
Would be nice to have a custom logger which logs additional information, maybe in different formats to custom files.

Ideas:
- Log multiple servers to one file.
- Add a timestamp for each message.
- Output JSON, XML, etc. if needed.

**Comment by BraisGabin** [comment]
`tail -f log.txt | add_time_of_each_line.sh >> our_improved_log.txt`

**Comment by BraisGabin** [comment]
Some Klei news about this topic: http://steamcommunity.com/app/322330/allnews/

They added the `-backup_logs` flag.

**Comment by thasmo** [comment]
Recently they added a more or less useful timestamp to the chat log and in combination with existing tools like logstash etc. this issue seems like a big overhead and possibly a waste of time anyway. For now I think we should concentrate on other things and if needed we can re-open this with a more specific goal.
