### ISSUE TITLE
LEVELDATA_OVERRIDES is being ignored

### ISSUE THREAD

**Issue by dbiagi** [yeet-zone/docker-dontstarvetogether#124]
I know that WORLD_PRESET functionality was dropped, but as mentionent in #108, the contents of LEVELDATA_OVERRIDES should still be dumped on leveldataoverride.lua file.

But it seems that this property is being ignored because no leveldataoverride.lua was generated in the container.

Path to reproduce this behavior:

```sh
#!/bin/sh
CUSTOM='return {
  override_enabled = true,
  overrides = {
    summer = "veryshortseason"
  }
}'

docker run --rm \
  -e TOKEN="YOUR_TOKEN" \
  -e MODS="378160973" \
  -e LEVELDATA_OVERRIDES="$CUSTOM" \
  -p "10999:10999/udp" \
  --name dst-test \
  dstacademy/dontstarvetogether:0.7.1 --update=all
```

After the container is ready:

```sh
docker exec -it dst-test find / -name leveldataoverride.lua
```

No files were found.

Am I doing something wrong?

**Comment by BraisGabin** [comment]
I tried your example and it worked with the version `0.8.0`

**Comment by dbiagi** [comment]
Oh, sorry. I was using the old 0:7.1.
The 0.8 image uses the LEVELDATA_OVERRIDES as expected. 
Thank you for the help.
