### ISSUE TITLE
Add GitHub Link in Docker Hub

### ISSUE THREAD

**Issue by rubidot** [yeet-zone/docker-dontstarvetogether#128]
I've seen other Docker Hub pages with a GitHub link on the right. It would be nice to have that on this Docker Hub page

https://hub.docker.com/r/dstacademy/dontstarvetogether/

**Comment by BraisGabin** [comment]
That's strange. Don't we have active the automated builds, @thasmo?

**Comment by thasmo** [comment]
I fear there's nothing we can do about it at present, but thanks for your participation @rubidot!
