### ISSUE TITLE
Set caves modoverride.lua and port dynamically

### ISSUE THREAD

**Issue by ghost** [yeet-zone/docker-dontstarvetogether#130]
In a similar light as #33, I think we should be able to use the SHARD_IS_MASTER variable to set the LEVELDATA_OVERRIDES and the SERVER_PORT when they are not manually specified by the user.

In cases where the server is master, it would default to a forest configuration.
In cases where the server is not master, it would default to a caves configuration.

**Comment by thasmo** [comment]
In general I like the idea, although I'm a bit cautious to not integrate too much magical and automatical configuration to avoid complexity and to not make it too confusing for users, basically. Let me think about it.

**Comment by thasmo** [comment]
@lego-engineer, we've migrated this project over to https://github.com/yeetzone/ and along the way we implemented a new environment variable `WORLD_PRESET` which makes it easier to setup pre-defined worlds, like `Caves` or `Lights Out` etc. See https://github.com/yeetzone/docker-dontstarvetogether/blob/master/docs/configuration.md for the possible values.
