### ISSUE TITLE
Interactive Configuration Script

### ISSUE THREAD

**Issue by ghost** [yeet-zone/docker-dontstarvetogether#131]
I've been working on an interactive python configuration script for use with this docker image. 

The goal of the script is for it to ask the questions and then generate a docker-compose and the *.env files based upon the user's responses. Would this script be of interest to this project?

**Comment by thasmo** [comment]
Hey @lego-engineer and thanks for your question! We're probably not going to integrate the script into the project but if you open-source it somewhere, we'd be more than happy to mention and link to it in our documentation, so people can easily find and use it, if they want to! What do you think?

**Comment by ghost** [comment]
Hello @thasmo!
That sounds like a great idea. I'll spend a little time making it an official python package and then send the relevant information on to you guys.

**Comment by ghost** [comment]
Hey @thasmo!

[Here](https://gitlab.com/lego_engineer/dst-server-deploy) is a link to my gitlab repo with the project.

My general intent was for the script to streamline the server deployment process for those new to docker and those who want a server on the more basic end of the spectrum. As such it will build the proper docker-compose and *.env files for almost all of the configuration options specified in [here](https://github.com/fairplay-zone/docker-dontstarvetogether/blob/develop/docs/configuration.md). However, since I wanted to keep it more on the generic end, and did not want to have too many prompts, I decided not to include all options (TICK_RATE, NAME_PREFIX, etc). I figured that people who want specialized stuff like that will know enough to be able to manually add these details. As time goes on and you guys update your image, I will update my script.

### General Script Info
* Downloadable from my gitlab or pypi. 
* Creates a console command `dst-server-deploy` which asks questions from which it generates the `docker-compose.yml` and `*.env` files.
* Python3.5+ compatible. (It should work for older versions, but I didn't test)
* Uses argparser to accept cli arguments to streamline operation. 

### Future Plans
* Test against 3.0 - 3.5 python verions.

**Comment by thasmo** [comment]
I've added the link to reference section of the readme. 👍
