### ISSUE TITLE
The server is on a different version than you.

### ISSUE THREAD

**Issue by Nixellion** [yeet-zone/docker-dontstarvetogether#133]
Hi! 

Trying to make this work. I dont see my server in the list of servers and  when I try to connect directly by ip (c_connect) it says that the server is on a different version than me. I tried restarting docker container as it says that it should run the update, but it's still on the wrong version.

What did I miss?

**Comment by Nixellion** [comment]
Solved by logging into docker's cli using `docker exec -it cont_name /bin/bash` and executing `dst-server start --update=all`. Restarted container and it's up to date now and shows up inthe server list in the client.

But have another issue - "The server is not responding. Please try again." when I try to connect.

**Comment by Nixellion** [comment]
Okay, my bad, forwarded port 10999 which I shouldn't have done. Problems solved! Thanks everyone! :D

**Comment by thasmo** [comment]
Sorry for chiming in so late but I'm glad you figured it out. Unfortunately the project is not actively maintained at present but I'm happy to hear that the docker image still works although with some effort spent. Also I believe that `--update=all` is an option which needs to be set explicitely to enable game updates at all, otherwise it runs on the version which was released at built time of the image.

**Comment by Nixellion** [comment]
@thasmo Yeah, I saw the date of the last commit and was not expecting a fast reply. There's not much effort actually, just probably a bit of lack of experience with docker.

To make it properly do I have to somehow add something to the `docker run` command so it's created with `--update=all` already at start?

**Comment by thasmo** [comment]
@Nixellion I recommend you use `docker-compose` to configure how to run the image using a `docker-compose.yml` file; review the [examples](https://github.com/fairplay-zone/docker-dontstarvetogether/tree/develop/docs/examples). You can also use `docker run` and simply add `--update=all` to the command I believe.

**Comment by Nixellion** [comment]
@thasmo Cool, thanks!
