### ISSUE TITLE
Move savegame to dedicated server?

### ISSUE THREAD

**Issue by frankruegamer** [yeet-zone/docker-dontstarvetogether#134]
I have a local savegame that I played on with some people for a few hundred days that I want to move to a dedicated server because of the growing lag.

What I did was to generate a default world using the docker instance and replacing the "save" folders. After getting the mods and modoverrides to work, I have some problems when trying to migrate the cluster: The world starts up just fine but it didn't remember my character, or any of the other characters. I tried to copy the session folder from my local client_save folder to the server but that didn't help either.

My question is, what is the easiest way to migrate a savegame to a docker-compose instance?

Or what do I need to do to make clients have the correct character?

**Comment by thasmo** [comment]
@frankruegamer, we've migrated this project over to https://github.com/yeetzone/docker-dontstarvetogether. If you still need help, feel free to open a thread in https://github.com/yeetzone/docker-dontstarvetogether/discussions to dicuss. Also, it sounds like your issue maybe is related to #138. Sorry for the late reply!
