### ISSUE TITLE
Bind mount cause bug on windows

### ISSUE THREAD

**Issue by hexaJer** [yeet-zone/docker-dontstarvetogether#137]
Hello, I tried to configure a server with docker desktop on windows 10.
World is badly generated, water appair under trees, grass, rocks, etc... and sometimes under you and you can only walk over water. ([like that](https://www.youtube.com/watch?v=7f81w8IPcEY))

I search for a long time with all differents configurations, and basic was finally the only one working properly. I came to understand that the **bind mount** was the problem and all configs work fine on windows if we remove `volumes` lines from **docker-compose.yml**. 

I also tried to run it with administrator privileges but it's the same.

**Comment by thasmo** [comment]
@hexaJer, I've had this issue several times too when running Docker on Windows. Unfortunately I was not able to find a fix for it but I never encountered the problem when running Docker on Linux.

**Comment by cferrey** [comment]
I am also experiencing the exact same problems when trying to run this on Docker in Ubuntu.  I imagine this is a permissions issue.  I have tried copying the files out of the container into a new folder, setting it as a bind mount, and recursively changing the ownership permissions on all of the files to 999:999 (which seems to match the user "steam" inside the container).  However, this does not fix the issue.

Would it be possible to add the ability to configure PUID/PGID via environment variables when using this container via docker-compose?  I wonder if that would help (as we could set permissions correctly).

**Comment by minzhi3** [comment]
I have same problems when running Docker Desktop on Win and Mac.
Maybe it is bug on filesystem between different OS.
It is solved by using **docker volume** instead of **bind mount**

**Comment by thasmo** [comment]
@minzhi3 Would you mind sharing how exactly you create/use/attach the volume? Thanks a lot!

**Comment by minzhi3** [comment]
@thasmo 
This is my docker-compose file
```
version: "2"
services:
  world:
....
....
    volumes:
      - dst_world:/var/lib/dsta/cluster

volumes:
  dst_world: {}
```
then docker VM will create and attach the volume automatically
```
$ docker volume ls
DRIVER              VOLUME NAME
local               dst_dst_world
```
While in this way, files in the volume are managed by docker VM, so they cannot be edited directly. 
Hope it helps

**Comment by thasmo** [comment]
We migrated this project over to https://github.com/yeetzone/docker-dontstarvetogether but unfortunately I was not able to figure out the issue with the corrupted world generation. It seems to be related to bind mounts and or volumes when running Docker for Windows. This issue does not occur on Linux.
