### ISSUE TITLE
Player progress lost when resuming with another image

### ISSUE THREAD

**Issue by hiendv** [yeet-zone/docker-dontstarvetogether#138]
Hi,
I was trying to run `docker-compose down` followed by `docker-compose up` and expected everything to be the same but something went wrong. Since the world files are persisted, it's okay but I have to pick my character again and the inventory is gone.
Is this an expected behavior or not? If it is, how to resume players after updating the docker images?
Thank you.

**Comment by BraisGabin** [comment]
No, it's not an expected behavior at all...

I didn't hack around DST lately but maybe they moved the user data to a different file...

Is this issue reproducible if the server doesn't have mods? If you provide me a way to reproduce the error I can check what's going on this weekend.

**Comment by fhebuterne** [comment]
Same issue, with shard config example and docker-compose.
When i use docker-compose up -d, server start without issue and i can play but when i write docker-compose down and relunch with docker-compose up -d, server start with world but we lose our characters and inventory.
I don't understand becase player file are always present in ./overworld/save/session/XXXXXXX/ID_PLAYER but after each stop/start, i see it create new file with incrementation like 000000002, 000000003, 000000004 etc...

**Comment by ALiangLiang** [comment]
same problem here
maybe something need mount too.

**Comment by thasmo** [comment]
Not sure what the reason for this is. Player sessions are stored in `/save/session/` afaik and those get mounted via a volume, so technically it should work.

**Comment by magictext** [comment]
the same problem.
may be the invalid stop action is the reason of the problem?

**Comment by mloureiro** [comment]
Just a small note, has the OP mentions the `docker-compose down`, although for me simply stopping the containers `docker-compose stop` will do this behavior. (I'm using a shard with forest and cave based on the docs)

**Comment by MaeIsBad** [comment]
Here is a quick hack that I think should solve this(it worked for me): manually append
```
[ACCOUNT]
encode_user_path = true
```
to the /var/lib/dsta/cluster/whatever/server.ini file and make it read only.

It should be an easy fix to just automatically append it if anyone wants to make a commit

**Comment by thasmo** [comment]
We've migrated this project over to https://github.com/yeetzone/docker-dontstarvetogether and have updated it along the way. The mentioned quick hack was incorporated into the migrated project as this option should help in theory in all environments and operating systems on which Docker runs.
