### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by rosemaryehlers** [yeet-zone/docker-dontstarvetogether#139]
Is it possible the game updated recently, and the docker image is out of date? I'm getting an error message when I try to connect: "The server is on a different version than you. Please check that your game version is up to date."

I have checked Steam, and it doesn't look like my DST needs any update.

**Comment by thasmo** [comment]
@rosemaryehlers, that's a possibility. Did you start the server with `dst-server start --update=all` so it updates game files and mods on boot? That should keep it updated actually.
