### ISSUE TITLE
Cannot connect to Caves server ("Server is not responding")

### ISSUE THREAD

**Issue by repomaa** [yeet-zone/docker-dontstarvetogether#140]
From the logs of both shards everything looks fine. I made sure to forward the same ports as in the container to the host. All ports are open on the server (it's a vserver, not behind nat). Still, if i go through a sinkhole i get the error "Server is not responding".

- Here's my [overworld.log](https://p.jokke.space/4ozrwO/)
- Here's my [caves.log](https://p.jokke.space/7l0k/)
- Here's the output of [`docker service inspect dst_overworld`](https://p.jokke.space/SPD/)
- Here's the output of [`docker service inspect dst_caves`](https://p.jokke.space/4fEt/)

**Comment by thasmo** [comment]
@repomaa We're migrating our DST dockerfile and image over to https://github.com/yeetzone/docker-dontstarvetogether and also have updated it along the way. Feel free to check it out and see if it solves your issue.
