### ISSUE TITLE
How do I use volume to persistent data

### ISSUE THREAD

**Issue by seethefruture** [yeet-zone/docker-dontstarvetogether#148]
How do I use volume to persistent data? Where  are the volume paths in continer

**Comment by thasmo** [comment]
@seethefruture Have a look at https://github.com/yeetzone/docker-dontstarvetogether/blob/master/docs/recipes/basic/docker-compose.yml, the game data is mounted at `/data`. The server configuration and session files are stored in `/opt/storage` as you can see in https://github.com/yeetzone/docker-dontstarvetogether/blob/master/build/Dockerfile

**Comment by seethefruture** [comment]
cool! thanks.
