### ISSUE TITLE
Why mod biome won't be created in server?

### ISSUE THREAD

**Issue by neuron42** [yeet-zone/docker-dontstarvetogether#151]
Here are my master.env file and caves.env file

```
TOKEN=.............
NAME=nDontStarve
LANGUAGE=zh
PASSWORD=233
GAME_MODE=endless
INTENTION=cooperative
PAUSE_WHEN_EMPTY=true
SHARD_ENABLE=true
SHARD_NAME=Master
SHARD_ID=1
SHARD_IS_MASTER=true
SHARD_MASTER_IP=127.0.0.1
SHARD_CLUSTER_KEY=233
WORLD_PRESET=SURVIVAL_TOGETHER
MODS=1699194522,199174650
```

It seems mods wont be loaded at the first time of "docker run".Because only if i tried to reboot the container,these mods will be enabled.

In my test, none of the modules involved in terrain generation worked

**Comment by thasmo** [comment]
@neuron42, mods seem to work for me. Could it be that the mod ID `199174650` is invalid? I can't find a Steam workshop mod with that ID. Please feel free to respond and reopen the issue if the problem persists. Thank you!
