### ISSUE TITLE
Trap the signals

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#19]
It seems that `dontstarve_dedicated_server_nullrenderer` don't react preaty well to the signals. If we write `c_shutdown(true)` at the game console we get this nice log:

```
c_shutdown(true)
ConsoleInput: "c_shutdown(true)"
c_shutdown      true
Serializing world: session/F79FF192BBBCB9EC/0000000003
Could not unload undefined prefab 0x1872ccf0 (FROMNUM)
Updates 0Seconds elapsed: 14.4339 fps:0
[Steam] UserDisconnect successfully sent for steamid ''
Collecting garbage...
lua_gc took 0.11 seconds
~ShardLuaProxy()
~InventoryLuaProxy()
~NetworkLuaProxy()
~SimLuaProxy()
lua_close took 0.15 seconds
CurlRequestManager::ClientThread::Main() complete
HttpClient2 discarded 1 callbacks.
Shutting down
```

If we just send a `Ctrl + C` signal there isn't any new line in the log :cry:

So, we need to trap this signals and send to the `dontstarve_dedicated_server_nullrenderer` the proper commands to close cleanly.

We must investigate if `c_shutdown(true)` is the best option. I opened a topic to ask about this: http://forums.kleientertainment.com/topic/62055-which-is-the-cleanest-way-to-stop-a-dst-server/

Some links provided by @thasmo about how to deal with the signals:
- https://rimuhosting.com/knowledgebase/linux/misc/trapping-ctrl-c-in-bash
- http://hacktux.com/bash/control/c
- http://redsymbol.net/articles/bash-exit-traps/
- http://ubuntuforums.org/showthread.php?t=1546996

**Comment by BraisGabin** [comment]
After #31 I think that this can be moved to the milestone `0.5`. This is a very important feature.

**Comment by thasmo** [comment]
Now, as we can send commands to the game console, this can be achieved quite cleanly - and this is great. We trap the `SIGTERM` signal and send a `c_shutdown(true)` command to the server, which will shut it down gracefully. :+1:
