### ISSUE TITLE
Auto-update game-files unobtrusively

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#2]
Updating the game- and mod-files should happen as ressource-efficient and unobtrusively as possible. The idea is to have a separate service/container checking for updates and either have it inform game-servers about the update or even shut them down, perform the update and boot them again. Best option would be to perform this when no players are on the servers.

**Comment by thasmo** [comment]
Get released build-id:

``` sh
rm -f /Steam/appcache/appinfo.vdf
./steamcmd.sh +login anonymous +app_info_update 1 +app_info_print 343050 +quit
# branches.public.buildid
```

Get installed build-id:

``` sh
cat ./DoNotStarveTogether/steamapps/appmanifest_343050.acf
# buildid
```

Compare both and update if mis-match.

**Comment by thasmo** [comment]
[jq CLI JSON-Processor](http://packages.ubuntu.com/search?keywords=jq)

**Comment by BraisGabin** [comment]
The user can update the game and/or the mods right now. Must we make any type of cron to check the updates? Is this inside the scope?

I mean, must we do something more for this issue?

**Comment by thasmo** [comment]
The issue is quite a complex one I think. I've spent some hours already on investigating how this could be achieved in a Docker context. Everything needed to make containers/servers auto-update itself related to this issue. If we want to integrate this in a graceful way, we should not restart a server if players are on the server, but we can only find out, if players are on the server, by writing/using a DST mod, which gives us this information.

So, overall, the scope of this issue is:
1. Determine if an update is available. (cron-like)
2. Determine if server is empty. (DST mod)
3. Restart container and run update.

We can solve 1. and 2. with some effort, but for 3. I don't have a good idea for now. We could skip 2. for now, to make it a bit easier.

**Comment by BraisGabin** [comment]
hmmm... We have access to the game console... I think that we can write something to know if there is someone.

How can we manage that all the shards have the same version? If each container updates itself we can have that problem.

We can archive this in the compose context. Just update the image. As always I prefer the image update :joy:.

I think that for this PR we can only make tools to help the users to update the server, we can't update it automatically. The tools can do the same
- Tell you how many users are inside the server right now.
- Tell you which is the version of the dst running right now.

With this two tools the user can decide how to update the server. Once we have this tools we can create something in the suite or even an "auxiliar" image to manage the update.

**Comment by thasmo** [comment]
How would you access the game console on a running server? We still have the problem not having a solution for this. Because if we had, we could also shutdown the server gracefully and probably do more cool stuff.

We can split the scope of the issue into multiple independent issues/PRs, that's no problem, but the actual goal of the issue is to provide a solution to automatically update containers.

There's a function called `c_listallplayers()` which can be executed on the game console to get the current active players. But how would we run this automatically without attaching to the container by hand?

**Comment by BraisGabin** [comment]
Ok! This is my new task :D run console commands.

**Comment by BraisGabin** [comment]
I'll check later but this seems to be the way: http://serverfault.com/q/188936

**Comment by BraisGabin** [comment]
Done!

Ok, now we can know the number of users more or less easily. So, how can we implement this feature? it's enought with `dst-server --info` (info with the number or users and possible other info) and `dst-server --version`?

**Comment by thasmo** [comment]
To get the currently released build version it's not needed to install the game, actually:

``` sh
rm -rf /home/steam/Steam/appcache/*
/home/steam/steamcmd.sh +login anonymous +app_info_update 1 +app_info_print 343050 +quit | grep -Po -m 1 "\"buildid\"\s*\"(.*)\"" | grep -Po "\d*"
```

This will fetch and return the build version of the public branch of the game.

**Comment by thasmo** [comment]
After some recent research I think using the docker-native `HEALTHCHECK` feature in combination with [`willfarrell/docker-autoheal`](https://github.com/willfarrell/docker-autoheal) will result in a clean and docker-friendly way to control automatic updates.

Basically `HEALTHCHECK` runs a shell-script inside a container which returns `healthy` (0) or `unhealthy` (1) and if the container is unhealthy for a defined period of time, `willfarrell/docker-autoheal` will restart the container. 

In the future `willfarrell/docker-autoheal` possibly won't be needed anymore if Docker gets this feature baked in.

There are also several other `autoheal` containers, but `willfarrell/docker-autoheal` seems to be the most used/robust one.

**Comment by Turbine1991** [comment]
If anyone's looking for a more robust way retrieve data from the ACF output, such as the buildid of another branch - I've made a simple ACF to JSON formatter, with examples.

https://github.com/Turbine1991/cpp_steam_acf_to_json
