### ISSUE TITLE
Mods are not installed properly

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#20]
When starting the server, the console shows some error:

```
Download server mod 492173795
Could not open directory [../mods/workshop-492173795] 2 (/var/lib/steam/DoNotStarveTogether/data)
Failed to create mod folder [../mods/workshop-492173795]. Sleep and try again...
```

Mods can't be written to disk.

**Comment by BraisGabin** [comment]
ARG! We need a test suit >_<! To fix this issue we just need to add `dsta` user to the `steam` group, I think.

**Comment by thasmo** [comment]
Does this problem indicate that using two users is not ideal, or not?

**Comment by BraisGabin** [comment]
Yes, I think that too. Work with groups seems a _bit too much_.

**Comment by thasmo** [comment]
So, I propose to keep the `steam` user for doing all the stuff. We could migrate all files to `/var/lib/steam/`.
