### ISSUE TITLE
Tagging Strategy

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#21]
Docker doesn’t have wildcards like in `composer` or `gradle` but they can move the tags so, more less we can accomplish the same. An example: https://hub.docker.com/r/library/postgres/

When we publish the `v1.0.0` we must create 3 tags: `1`, `1.0` and `1.0.0`. And if we creates a `v1.0.1` we create the tag `1.0.1` and we move the tags `1`  and `1.0` to point that image. This way if someone say `dstacademy/server:1` he is going to get all the improvement we’ll make in the `v1.X` but if he want the tag `1.0.0` he is not going to get any automatic update dsta update. But he is going to get images updates because we are going to update the image with the last version of dst.

Other thing, I didn’t see any official image tag with the `v`so we can remove it. For me seems cooler with it but…

I think that once we are agree we must write down how to tag the images, because it’s not so trivial as it seems.

**Comment by thasmo** [comment]
True. Here are my additional thoughts.
- I really like the `v` prefix for tags on Github, but we should create Docker tags without `v` prefix.
- The Docker `latest` tag should correspond to the latest commit on the `master` branch.
- Create a new Docker tag `next` which corresponds to the latest commit on the `develop` branch.

A new release `major.minor.fix` should create one new Docker tag and update four existing tags, as you've already mentioned - e.g. `v1.2.4` builds/updates these Docker images:
- `1.2.4`
- `1.2`
- `1`
- `latest`
- `next`

**Comment by BraisGabin** [comment]
I agree: Git tags with `v` docker tags without. I like your idea about `latest` and `next`. Is `next` any kind of convention? Is there any convention? May I propouse `snapshot`?

**Comment by thasmo** [comment]
Not sure if there's a convention, but `next` fits nicely to `latest` I thought. `snapshot` doesn't really tell what snapshot it is. Is it a nightly snapshot? A snapshot of a specific date? `latest` is a convention in the Docker ecosystem and I've read it should point to the latest stable release - if that's true, we're doing it wrong at the moment. It also makes sense to point to the latest stable release if you use the image `dstacademy/server` without tag. You should opt in to pre-releases explicitely, and `dstacademy/server:next` seems appropriate.

**Comment by BraisGabin** [comment]
Sure, latest the las stable. And it have sense `latest` and `next`. We are doing wrong because we don't have a stable version yet: `0.`

**Comment by thasmo** [comment]
`latest` is just a synonym for last released (newest) version and `next` is a synonym for the last commit.
