### ISSUE TITLE
Beta images

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#22]
With beta images I don't mean beta versions of our code I mean the bet version of the game. I think that we can install them with a `-beta` in `steamcmd.sh`.

The tag name can be the same as the normal version but ending with `-beta`.

**Comment by thasmo** [comment]
That could be a candiate for using [build arguments](https://docs.docker.com/engine/reference/builder/#arg).

**Comment by thasmo** [comment]
Seems like there are [no public beta branches](http://forums.kleientertainment.com/topic/62138-steam-beta-branches/) available at the moment.
