### ISSUE TITLE
Wishlist for Klei

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#27]
- [ ] Make path of mods-directory configurable to be able to use read-only game files.
- [x] Move `adminlist.txt`, `whitelist.txt` and `blocklist.txt` out of the `save` directory.
- [x] nullrenderer should handle signals.

**Comment by BraisGabin** [comment]
This is our wish-list, right?

**Comment by thasmo** [comment]
Kinda. :D

**Comment by BraisGabin** [comment]
I love it! Hear us Klei! :grin:

**Comment by BraisGabin** [comment]
You must add that they must implement the signal trapping. I'm feeling dirty doing the workaround. And I'm sure that it'll don't like you.

You are more active at the forum. Is there any way to get their attention? I'm sure that they can solve it easily.

**Comment by BraisGabin** [comment]
They trap the signals! :dancer: :tada:.

**Comment by BraisGabin** [comment]
And they move the lists outside the save directory! :tada:

**Comment by BraisGabin** [comment]
We need answers for this: http://forums.kleientertainment.com/topic/64690-for-what-steam-ports-are-used/
And this: http://forums.kleientertainment.com/topic/63263-cave-server-gets-passworded-all-the-time/

**Comment by thasmo** [comment]
We should also track [this thread](http://forums.kleientertainment.com/topic/66125-port-remapping-problem/) regarding weird port behvior.

**Comment by BraisGabin** [comment]
I think that with #29 this issue is not so important and it can be closed. Anyway we need more information about the steam ports and the main port to take better decissions. Klei is not helping us...

**Comment by thasmo** [comment]
Regarding the `steam authentication` ports. I do not expose those ports publicly, when launching servers - so I guess they must be used internally, between server shards in a cluster.

**Comment by thasmo** [comment]
Closing this now as I think, so far, we're happy about how Klei changed things.
