### ISSUE TITLE
Validation for Environment Variables

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#28]
We can check some variables to see that they are setted with correct values and launch a warning otherwise.

For instance: `MAX_PLAYERS` must be a positive intenger or the correct values for `WORLD_PRESET`.

**Comment by thasmo** [comment]
Good idea. Should be fine to have some _soft_-checking of the variable-values, but it shouldn't be too restrictive in my oppinion.
