### ISSUE TITLE
Generate a cleaner settings.ini file

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#29]
We create a too verbose `settings.ini` right now. In the most cases we don't need all those options and the slaves servers need even less than the masters.

And I think that we can remove some settings too. I'm looking at `server_port`, `steam_authentication_port`, `steam_master_server_port` and `master_port` for the moment. And I saw [your post about autocompiler](http://forums.kleientertainment.com/topic/62703-auto-compiler-on-dedicated-server/). It can be other candidate.

**Comment by thasmo** [comment]
Yep, we should be really careful about what we disable here, because people still may have a use-case for those settings and/or we still need certain settings to run it in a special Docker context.

**Comment by thasmo** [comment]
Created a dedicated issue to discuss removing variables in #33.

**Comment by BraisGabin** [comment]
I'm not sure if this is a good idea. All the times that I try to implement this issue the code is far too complicated. Generate files is not easy nor clean. Is this important enought for add that complexity to the code?

**Comment by thasmo** [comment]
In my oppinion we don't need to create settings files with only the options which have been defined. It's okay for me to set all options with sensible defaults. So, you can close this if you wish. :)

**Comment by BraisGabin** [comment]
Hmmm, can we keep this open but without Milestone? I will close it if I decide not to. But I'm not sure right now.
