### ISSUE TITLE
Add the console command

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#32]
With #31 we have access to the console. So I think that we must give a way to connect to the console. Something like: `dst-server console`.

**Comment by thasmo** [comment]
So, on a running container it could be used like `docker exec -it <container> dst-server console "c_announce('hey')"` or similar?

**Comment by BraisGabin** [comment]
Hmmm I was thinking in a real console (I don't know how to implement it right now but...) but that have sense to. We can do something like `ssh` if you don't say any command it opens a console. If you type the command it just run that command.

**Comment by thasmo** [comment]
Currently it's already possible to attach to the game-console by running `docker attach ...` so I thought it would be nice to have a solution for sending commands to the game without attaching.

**Comment by BraisGabin** [comment]
That's true! `docker attach` do the trick. So yes, only to send commands without needing to attach.

**Comment by BraisGabin** [comment]
We must have to different options: read from input or directly from command. The good thing about the input is that you can redirect from a file `docker exec -it <container> dst-server console < something`

**Comment by thasmo** [comment]
This shouldn't be difficult to implement, right? Do you think we can squash this into v0.4?

**Comment by thasmo** [comment]
I mean, we only need the pipe-feature, so it's possible to pipe commands to the container.

**Comment by BraisGabin** [comment]
Yes. This one is easy. if they give us like arguments we only need to use the echo, and if they give us in stdin we just need to pipe it to the console pipe and that's it.

We can have it for `0.4`. Tomorrow or even this night if I don't want to sleep to early.
