### ISSUE TITLE
Remove unnecessary environment variables

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#33]
Figure out which variables we don't need and remove them.

Candidates:
- [ ] `SERVER_PORT`
- [ ] `STEAM_AUTHENTICATION_PORT`
- [ ] `STEAM_MASTER_SERVER_PORT`
- [ ] `AUTOCOMPILER_ENABLE`
- [ ] `SHARD_ID`

We need to be careful about what we remove, maybe there are relevant edge-cases for certain variables.

**Comment by BraisGabin** [comment]
I'm sure that `server_port` can be removed. If someone want a different one he can use docker.

I'm thinking in `master_port`. Server in different machines. They can expose different ports... But we must enforce that they use the same netword (Docker allow that) so the internal port is the same so it's not necesary.

`STEAM_AUTHENTICATION_PORT` and `STEAM_MASTER_SERVER_PORT` Are the ports of steam. How can be useful change that ports?

I really have no idea what the autocompiler is.

**Comment by BraisGabin** [comment]
I write a bit about the steam ports here: http://forums.kleientertainment.com/topic/64690-for-what-steam-ports-are-used/

As far as I can tell you need to set this ports only when you have more than one server in the same machine. With docker we can remove them. But I don't have any "official source" to prove this.

**Comment by BraisGabin** [comment]
And I'm trying it again: http://forums.kleientertainment.com/topic/64552-dedicated-server-settings-guide/?do=findComment&comment=728288

**Comment by BraisGabin** [comment]
I think that with #29 this issue is not so important and it can be closed. Anyway we need more information about the steam ports and the main port to take better decissions. Klei is not helping us...

**Comment by thasmo** [comment]
When I remember correctly we can't remove `SERVER_PORT` currently, when using a multi-world configuration, because DST somehow relies on those different ports.

**Comment by BraisGabin** [comment]
I think that we can close this issue. We removed all except `SERVER_PORT`.

**Comment by thasmo** [comment]
:+1:
