### ISSUE TITLE
Optimize repository names

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#35]
For a better forking experience and better identification overall we should rename the repository before releasing the final version. In addition the Docker Hub name should be clearer.

Suggestions for GitHub:
- `dst-academy/dst-server-docker`
- `dst-academy/docker-dst-server`
- `dst-academy/dont-starve-together-docker`

Suggestions for Docker Hub:
- `dstacademy/dont-starve-together`
- `dstacademy/dont-starve-together-server`
- `dstacademy/dst-server`

**Comment by thasmo** [comment]
With the introduction of some more repositories I thought we could maybe make all repository names more comprehensible.
- `dst-academy/docker-dontstarvetogether`
- `dst-academy/docker-steamcmd`
- `dst-academy/docker-charlie`
- `dst-academy/hubot-charlie`

There will be a `dst-academy/deployment-charlie` too, soon.

Not sure about what to rename `hosted` to, but it should also be more descriptive.

**Comment by BraisGabin** [comment]
I like those names.

In Docker hub we just remove "`docker-`".

We can check how the search works in Docker Hub. I mean, be sure that someone looking for "Don't Starve Together" finds our image.

**Comment by thasmo** [comment]
Search should be fine, there are other projects using `dontstarvetogether`. I think the Docker Hub also searches the `README.md` file.

We should maybe change the repository names as soon as possible to have them as stable as possible even before we release `1.0`.

**Comment by BraisGabin** [comment]
I agree, as soon as better.

**Comment by thasmo** [comment]
Seems like it's not possible to **rename** the repositories on the Docker Hub. Need to figure out a way for migrating which works best.

**Comment by BraisGabin** [comment]
I would create the new one, deprecate the old one. And once we launch 1.0 remove the old.

**Comment by thasmo** [comment]
Repository names have been renamed (on GitHub and Docker Cloud/Hub) for quite a while now and so far I'm not aware of any complaints.
