### ISSUE TITLE
Update game and mods by default

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#37]
The `start` command should use `--update=all` by default, so it will update the game and mods when booting. This is important, because if the server's game files are outdated, it is _not_ shown in the browser list.

**Comment by BraisGabin** [comment]
I don't like this but i'm going to implment it for now. I expend 60 seconds to launch the server with the `--update=all` flag. And this happens even when there isn't an update!

As soon as we fix #5 we must rethink this behaviour.
