### ISSUE TITLE
Consider setting no server-description by default

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#40]
Currently we set `SERVER_DESCRIPTION="Powered by DST Academy."` and although it seemed to be a nice default value in the beginning, some minor problems arise with this decision.

First, people might don't want a server description, which doesn't reflect their intention for the server. Simply said, they don't want to have `DST:A` associated with their server.

Second, it happens people run servers, we don't want to be related to. In other words, we don't want to be connected to people/servers, which reflect thoughts and/or values on us we don't belong to.

Setting no server description by default seems a better choice after all.

**Comment by BraisGabin** [comment]
I think that it's a good way to get a bit of impcat. If you care about your server you are going to set a description. If you don't care... well, the people is goint to see that there's something called "DST Academy".
