### ISSUE TITLE
Major changes in dedicated servers

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#45]
More info here:
http://forums.kleientertainment.com/topic/64211-game-update-166077-02112016/
http://forums.kleientertainment.com/topic/64212-dedicated-server-quick-setup-guide/

We need to research about how this affect our images.

**Comment by thasmo** [comment]
Not sure if that indicates any changes to dedicated server; seems like a normal server-setup to me. What do you mean exactly?

**Comment by BraisGabin** [comment]
If you read the second topic you will see that this is a big change. And it's not optional. A lot of people are having problems with it. They "improve" the shard management but it doesn't help for us because we run the shards in different (virtual) machines.
