### ISSUE TITLE
General Optimizations and Ideas

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#50]
- [ ] Reduce test-suite duration.
- [ ] Optimize and simplify directory-structure.
- [x] Improve documentation.
- [ ] Utility for `docker-compose.yml` generation. (Separate project.)
- [ ] Solution for pinning the DST version.
- [x] Check for missing features/variables/configurations.

Feel free to add/suggest what comes to your mind.
Final tasks will get their own issue/ticket.

**Comment by thasmo** [comment]
@BraisGabin, are there ways to reduce the test-suite duration? Would be awesome to trim that down if possible.

**Comment by BraisGabin** [comment]
I know... the problem is that nearly all the tests need the server running. And right now we don't know when this happen. For that reason we have huge sleeps.

I don't know if we can launch some sort of signal when we now that the server is running... That can be usefull for scripting too.

**Comment by thasmo** [comment]
Closing this for now because if we decide to tackle any of the mentioned things, we should create separate issues, otherwise I feel this issue won't be closed for a long time. :)
