### ISSUE TITLE
Optimize generation of cluster and server configuration files

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#51]
Currently the generation of the cluster and server configuration files does not create proper configurations under certain circumstances.

For example `SHARD_ENABLE` is only needed in the cluster configuration, but if it's not set for a secondary server, there won't be any shard-related settings written to the server configuration.

In general we should optimize and harden the generation of the configuration files so we can ensure it works for every possible situation.

**Comment by BraisGabin** [comment]
I'm not sure if I understand this issue correctly. You don't need to enable the shard in the slave servers?

**Comment by thasmo** [comment]
Yes, `SHARD_ENABLE` is only needed in the cluster configuration. But currently, with our server, it's also needed for every single server, otherwise some other options are skipped.

**Comment by BraisGabin** [comment]
The cluster configuration must be in all the servers: master and slaves. There's only one way to have only one cluster configuration: if you share the same volumen. Am I right?

**Comment by thasmo** [comment]
To be honest, I can't remember what the actual problem was. I'll close it for now and will open a new issue if it occurs to me again.

**Comment by thasmo** [comment]
We've gotten valuable feedback in #78 and the goal should be to simplify the configuration for creating sharded setups tremendously. If it's needed we should introduce separate configuration variables for running a sharded setup - it should just be easy to understand in the first place.
