### ISSUE TITLE
Support `backup_log_count` argument

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#55]
There's no official documentation about to be found, but `backup_log_count` replaces `backup_logs`. maybe it will be found [here](http://forums.kleientertainment.com/topic/64743-dedicated-server-command-line-options-guide/) some time soon.

**Comment by BraisGabin** [comment]
I can't find any information about this. Must we add it? And if we must: how? I don't know where it must be.

**Comment by thasmo** [comment]
Ye, I haven't found any information about it but it pops up when launching a server. When launching a server on the shell it says that `backup_logs` is deprecated and will be replaced by `backup_log_count`. I think it's an argument for the nullrenderer when launching the server. `dst-server start -backup_log_count 10`, although I haven't tried it yet.

**Comment by thasmo** [comment]
When booting a `0.5.0` container the nullrenderer prints `[WARNING] -backup_logs has been deprecated and replaced with -backup_log_count`.
