### ISSUE TITLE
Ideas for a new `state` command

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#57]
It would be nice to have a `state` command which provides various information about the server, mainly information which can change over time. It should not be used to retrieve server settings; those should already be known when starting the server.

**Some ideas:**
- [ ] `dst-server state --population` - Return the number of currently online players, e.g. `0` if empty.
- [ ] `dst-server state --day` - Return the current day number, e.g. `1` for the first day.
- [ ] `dst-server state --season` - Return the current season name, e.g. `summer`.

**Comment by BraisGabin** [comment]
I think that we can display all that info without flags. You can use grep if you want to filter the output.

**Comment by thasmo** [comment]
What format do you recommend?

**Comment by thasmo** [comment]
I still think it would be nice to have it separate, like it's also done with the new `version` command. Maybe we can display all information on `state` and dedicated output using the arguments:
- `dst-server state`: Display full state with all available data.
- `dst-server state --<option>`: Display single state value.

**Comment by BraisGabin** [comment]
I like your idea. Probably we can do somthing similar with `dst-server version`.
