### ISSUE TITLE
COPY all scripts at once

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#62]
We could mirror the final directory-structure within the `build` directory and use a single `COPY` to copy all files into the image.

This ...

``` shell
# Copy common scripts.
COPY /script/* /usr/local/bin/

# Copy entrypoint script.
COPY /docker-entrypoint.sh /entrypoint.sh

# Copy static files.
COPY /static $DSTA_HOME
```

will become this ...

``` shell
# Copy scripts.
COPY /root/* /
```

Thoughts?

**Comment by thasmo** [comment]
Oh, we probably can't use this for `COPY /static $DSTA_HOME` because it's dynamic. Do we have other options? We could at least merge the two first `COPY` commands.

**Comment by BraisGabin** [comment]
I think that the 3 `COPY`s are OK. They don't overwrite any file and I don't like to have the `entrypoint.sh` script in the `PATH`.

**Comment by thasmo** [comment]
So you don't like creating the final directory-structure outside the image and just copying that over?

**Comment by BraisGabin** [comment]
I really don't know if that would be easier or more difficult to maintain that the current structure. The problem is that we can't copy all in one command as you point out. So I think it would be better to keep the thinks the same as now.

**Comment by thasmo** [comment]
Agreed, we should leave it for now.
