### ISSUE TITLE
Evaluate mod flags

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#64]
Looks like there are two flags dealing with mod updates:

```
-skip_update_server_mods - skips the download of any mods or collections in the file
-only_update_server_mods - quits once the downloads are finished.
```

We only use `skip_update_server_mods`. Does it make sense to also support `only_update_server_mods`?
Not quite sure how they differ exactly.

**Comment by BraisGabin** [comment]
We use both: https://github.com/dst-academy/server/blob/develop/build/static/bin/update.sh

**Comment by thasmo** [comment]
Ah, I see. :)
