### ISSUE TITLE
Image with mods

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#67]
One thing that I like from Docker is the short downtimes that you have when you update your code. This is because you can create a new image with the new versions while the old version keep running. Once you built/pulled your image you just need to recreate the container.

This is very easy with Docker Compose: 

``` shell
docker-compose pull && docker-compose build --pull && docker-compose up -d
```

This is the reason I don't like the `--update` flag as default in `dst-server start`, but that is other topic.

With this idea in mind, it would be great to generate your image with the mods in it, instead of download or update them in the `entrypoint.sh`.

Problem: There are too much mods and you don't want all of them. Each server will want it's own set of mods.

A solution: We can use `ARG` and encorage our users to generate their own images setting in the `ARG` the mods that they want to download.

The main idea it to move all the long tasks into the image and, this way, we can have a faster boot.

**Comment by thasmo** [comment]
But `--update` is not a problem when using `docker-compose build --pull && docker-compose up -d`, is it?

Regarding the mods. I like the idea but keep in mind that often when enabling mods, it's also neccessary to set a custom configuration for the mods. An example can be found [here](https://github.com/dst-academy/hosted/blob/develop/server/modoverrides.lua).

One question comes up for me. Which `ENV` vars should be changed to `ARG` and why? Or, how do we argument which `ENV` should be an `ARG`? Could all `ENV`s be `ARG`s? Does that even make sense?

**Comment by BraisGabin** [comment]
No, `--update=all` is not a problem. But I always use `--update=none` because I want a fast launch and I update the game pulling or building the image.

I know that some mods need some configuration, but write the configuration is really quick. I think that it can be done in the `entrypoint`. Even more, you don't want to generate a new image only for change a configuration. But it seems legitimate that you must build a new image to install a new mod.

So, I think that the `ARG` must be related with the installation process, no the configuration.

**Comment by BraisGabin** [comment]
I'm thinking if we must have two different images. The vanilla and the "Modded".

We want to publish the vanilla image in Docker Hub.
The Modded is just a Dockerfile. The base image would be the vanilla version and it have the necesary lines to install mods using an `ARG` and configure them using an `ENV`. It would be used like this:

``` yaml
build:
  context: github.com/dst-academy/docker-dstmodded.git
  dockerfile: build/Dockerfile
  arg: i-dont-know-the-sintax
```

**Comment by thasmo** [comment]
I'm not totally sold on this yet but if you can whip up a small, working, and useful example, I may understand it better. I mean, i know how it works technically, basically - but I'm not sure this is the correct way for how the DST game is run via Docker.

What I don't understand is what the `docker-dstmodded.git` is for?

**Comment by thasmo** [comment]
Maybe you could fork `dst-academy/hosted` and change it to how you think it could work.

**Comment by BraisGabin** [comment]
What do you think about this: 

```
FROM dstacademy/dontstarvetogether:0.7.1
MAINTAINER DST Academy <support@dst.academy>

# Set build arguments.
ARG MODS
ENV MODS ${MODS}

RUN file_mods_setup=$DST_HOME/mods/dedicated_server_mods_setup.lua \
	&& > $file_mods_setup \
	&& for mod in $MODS; do \
		echo "ServerModSetup(\"$mod\")" >> $file_mods_setup; \
	done \
	&& dontstarve_dedicated_server_nullrenderer -only_update_server_mods
```

Building like this:
`docker build --build-arg MODS=378160973 -t stacademy/dontstarvetogether-modded ./modded`

or:
```
build:
  context: github.com/dst-academy/docker-dontstarvetogether.git
  dockerfile: modded/Dockerfile
  args:
    - MODS=378160973
```

I didn't create the PR because I must to refactor a lot of code to remove the code related with mods from the *Vanilla* version and add this code in the new version. If you like the idea I'll start with it.

**Comment by JemiloII** [comment]
what would be nice is to cache and layer the most used plugins, eg global positions, and then leave the rest to a volume we can attach. This way mods stay around for updates and build times don't get out of hand~
