### ISSUE TITLE
Support command with options only

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#71]
Starting a container with `docker run dstacademy/dontstarvetogether --option` looks like a nice addition.
(Skipping the `dst-server` command.)

e.g. the MySQL base-image does it this way:
https://github.com/docker-library/mysql/blob/a6f4c23621421bb708ad44616532d3d1cf44f6bf/5.7/docker-entrypoint.sh#L5-L7

Does that make sense for us? We probably only have `--help` as option, nothing else, right?

**Comment by BraisGabin** [comment]
I like this! How can we implement it? only for `dst-server start`? any idea?

**Comment by thasmo** [comment]
That's my proposal:
- `dst-server` maps to `dst-server start`.
- `dst-server --help` stays `dst-server --help`.
- `--help` maps to `dst-server start --help`.
- `dst-server start --help` stays `dst-server start --help`.
- `--update=*` maps to `dst-server start --update=*`.

So, in a nutshell:
Every call starting directly with an `-` (skipping `dst-server`) will run `dst-server start [options]`.

Whatcha say?

**Comment by thasmo** [comment]
So, for the `start` command we do have several options, which are `--update` and `--keep-configuration` (in the future), which makes this feature worthwhile to implement I believe.

**Comment by thasmo** [comment]
Added in 5c92b4e5d6788287a40bc81957cfc6294e473df0.
