### ISSUE TITLE
Overwrite configuration files by default and create an option to keep them

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#73]
It would be nice to have an option which enables overwriting of settings files. At the moment we check if settings files exist - and if they do, we skip creating the files. It would be nice to have an option disabling this and recreating/overwriting the files.

_Why?_ you ask.
Because then it's possible to kill the existing container and start a new one with other settings. Currently when starting a new container, it will **not** write any changed `ENV` variable to the configuration files, because if the files already exist, we skip the process.

We could have an option like `--force-configuration` or similar which could have a comma-separated list of files, including these:
- `cluster.ini` using `cluster`
- `<shard>/server.ini` using `server`
- `cluster_token.txt` using `token`
- `adminlist.txt` using `adminlist`
- `blocklist.txt` using `blocklist`
- `whitelist.txt` using `whitelist`
- `<shard>/modoverrides.lua` using `mods`

The command could be `dst-server start --force-configuration=settings,token` which will recreate the files `cluster.ini`, `<shard>/server.ini` and `cluster_token.txt`. All other files stay untouched.

This should be an opt-in argument which means the default is to not overwrite any existing files.

**Comment by BraisGabin** [comment]
Does it have any sense to keep the files? I mean, why don't we recreate the files always?

**Comment by thasmo** [comment]
`blocklist.txt` is where the game writes new lines when someone gets banned. So, in this case recreating this file really should be optional. `<shard>/server.ini` will also be written by the game to add the shard id, after the server starts. (This will happen when the id is missing I guess, so we could recreate this file without problems anyway, I guess.) All other files could probably be recreated, but I think it would be nice to have an option so people can just edit the files directly in the volume if they like. (Maybe they use external programs to modify them which have no direct support for Docker, etc.) And as `blocklist.txt` should not be overwritten by default I thought it makes sense to have the default setting to not overwrite any files.

**Comment by BraisGabin** [comment]
And something like `dst-server settings`? I don't like the idea to overlap `start`.

**Comment by thasmo** [comment]
It can only run on start, or? How would it work with a separate command on boot? What's your idea?

**Comment by thasmo** [comment]
It probably should be `--keep-configuration` and the default behavior would be to overwrite the files, e.g. `--keep-configuration` keeps all files, and `--keep-configuration=cluster,server` will only keep the `cluster.ini` and `<shard>/server.ini` files but overwrite all others.

**Comment by thasmo** [comment]
@BraisGabin What do you mean by using `dst-server settings` instead of using an option on `dst-server start`? The files are being generated on start, so I think it needs to be an option on the start command and cannot be a separate command.

**Comment by BraisGabin** [comment]
I must say that I like the `--keep-configuration` idea. And by default overwrite all the files. It's better than a new command.

**Comment by BraisGabin** [comment]
What do you think about this:

Keep `blocklist` by default and overwrite the others by default. (We must document this exception but I think that it have a lot of sense)

Add `keep-configuration` and `overwrite-configuration` (or `force-configuration`) to set which files you want to keep/overwrite.

Must we keep `whitelist` and/or `adminlist` by default too?

**Comment by thasmo** [comment]
Keeping the `blocklist` is understandable for obvious cases, but I think overwriting all files by default is a sane default for a Docker-related context. Having exceptions in the first place, also when documenting them, can be confusing imo. More confusing that describing that all files are reset by default and configuration needs to be adjusted accordingly to keep specific files. We should overwrite all files by default and add an example to the docs, showing how to preserve the `blocklist` and other files. This also fits nicely with the `update` arguments of the `dst-server` command, which does not update game or mod files by default.

**Comment by BraisGabin** [comment]
Ok, so you prefer to overwrite all and document that the user probably wants to keep blocklist instead of explain that blocklist is an exception in "overwrite all".

I must say that I see the pros and the conts in both cases so... If you prefer overwrite all I'm ok with that.

**Comment by BraisGabin** [comment]
We can close this issue now, right?

**Comment by thasmo** [comment]
I think so, yes.
