### ISSUE TITLE
Common options in shard could be clarified

### ISSUE THREAD

**Issue by plule** [yeet-zone/docker-dontstarvetogether#78]
As someone who deployed a server while knowing next to nothing about dst, I ran into the following issue, before realising what was contained in the shared cluster.ini file:

Following the sharded example, the overworld did not have the MASTER_IP setting. Unfortunately it was the quicker to launch, it created the cluster.ini without MASTER_IP and when the underworld was launched, it did not recreated cluster.ini so it missed MASTER_IP. This problem was not obvious to me since I had no idea they shared the cluster config.

After having corrected this it failed with "bad password" when travelling to a cave because of an issue unrelated to passwords, but since I did not know the password was shared in the cluster.ini files, I tried some useless things like disabling the password in the slave server.

I see two way to handle this:
- Documenting what options should be shared in the global doc, and having a common "shard.env" file in the sharded example.
- Having only the master server creating the cluster.ini, and having the slave waiting for it (with a common volume just for cluster.ini in case the user map their datas to different volumes?)

**Comment by BraisGabin** [comment]
I think that this is related with #51.

I developed that behaviour and I must say that I didn't think in someone using the same volume for both servers. If you use a volume per container it just works.

But, as you pointed out, the documentation is the main problem here. The example shares the volumes so anyone trying to use this project will do that error.

Is there any good reason to share the volumes? If there is I'll fix the code to handle this option. If there isn't a good reason I think that fix the sample is the best way to fix this problem.

**Comment by thasmo** [comment]
@plule, thanks for bringing this up. Unfortunately the examples are outdated and this is why you encountered them to not work in the first place. I'm on it tho. Second, @BraisGabin is correct that this is related to #51. We should handle the creation of the various configuration files in a more robust way.

**Comment by thasmo** [comment]
As a first step I've updated the shard example configuration, which should work now. ;)

**Comment by plule** [comment]
OK thank you :)
It should be enough I think, I don't think someone would map two different images volumes to the same directory now that it's not documented like this.
