### ISSUE TITLE
leveldataoverride.lua support?

### ISSUE THREAD

**Issue by SiBorya** [yeet-zone/docker-dontstarvetogether#84]
Is it possible to add "leveldataoverride.lua" support, since the dst client now create "leveldataoverride.lua" rather than "worldgenoverride.lua".

**Comment by thasmo** [comment]
Oh, absolutely. Do you know, is there any documentation about it?

**Comment by BraisGabin** [comment]
The documentation... That thing that Klei never writes :P.

Yeah, if there's some documentation the change should be easy.

**Comment by thasmo** [comment]
What I understand is that the `leveldataoverride.lua` file replaces the `worldgenoverride.lua` file completely; and has more options.

**Comment by thasmo** [comment]
Implemented the change in #85 which will be merged soonish.
