### ISSUE TITLE
How to configure different worlds leveldataoverride.lua

### ISSUE THREAD

**Issue by turingking** [yeet-zone/docker-dontstarvetogether#88]
I have multiple worlds, each of which is not the same. How can i configure it?

**Comment by thasmo** [comment]
You can use the environment-variable `LEVELDATA_OVERRIDES` to set the `leveldataoverride.lua` file's contents for each server/container separately.

**Comment by turingking** [comment]
@thasmo I mean in the same docker-compose.yml file, how to configure multiple servers

**Comment by thasmo** [comment]
This should be possible by using [`variable substitution`](https://docs.docker.com/compose/environment-variables/). You have to use a different variable for each server tho, but that should work.

**Comment by turingking** [comment]
@thasmo I'm sorry, I do not know what to do. I observe your example, start.sh and leveldataoverride.lua and modoverrides.lua. They are not bound to a world.
I try to add MODS_OVERRIDES = mymodoverrides.lua in the world.env file, but it does not take effect

**Comment by turingking** [comment]
f you do not add in start.sh, it will not be configured successfully. But start.sh can not distinguish between the world

**Comment by turingking** [comment]
I tried [variable substitution](https://docs.docker.com/compose/environment-variables/#substituting-environment-variables-in-compose-files)， can not take effect.
Log output has
`shell
main         | [00:00:05]: ERROR: Failed to load modoverrides.lua
`

**Comment by turingking** [comment]
Sorry, I'm not familiar with shell scripting。I now understand how to do it

**Comment by turingking** [comment]
Again sorry, I tried a variety of ways to replace variables for each server. Can you write a demo?

**Comment by thasmo** [comment]
I will help you in about 9 hours. :)

**Comment by BraisGabin** [comment]
https://github.com/dst-academy/docker-dontstarvetogether/tree/develop/docs/examples/multiple Here you have a demo. It doesn't touch the `leveldataoverride.lua` but you can get the general idea.

**Comment by turingking** [comment]
@thasmo Thank you very much, I have tried to run your example, but they can not load leveldataoverride.lua and modoverrides.lua.
 My approach is: in your example, change the token for my own token, then sh start.sh. Then observe the generated leveldataoverride.lua and modoverrides.lua. Very frustrating that it does not work.
@BraisGabin This example is very simple. I need to build multiple worlds, each of which has different leveldataoverride.lua and modoverrides.lua.

**Comment by turingking** [comment]
I try to do this, remove `MODS_OVERRIDES` in the world.env file, add `MODS_OVERRIDES =` in the modoverrides.lua file header, change the contents of start.sh:

` #!/usr/bin/env bash` 

` cat  modoverrides.lua >> world.env` 

` docker-compose up -d` 
It can work

**Comment by thasmo** [comment]
@turing-king, you need to adapt your `docker-compose.yml` file similar to this:
```yml
version: "2.2"
  services:
    world:
      environment:
        - LEVELDATA_OVERRIDES=${LEVELDATA_OVERRIDES_ONE}
        - MOD_OVERRIDES=${MOD_OVERRIDES_ONE}
```

And in your bootstrap script you need to use:
```sh
#!/usr/bin/env bash
export LEVELDATA_OVERRIDES_ONE=$(< leveldataoverride.lua)
export MOD_OVERRIDES_ONE=$(< modoverrides.lua)
docker-compose up -d
```

Untested, but I hope you get the basic idea. You have to define separate variables for every file and use them inside the `docker-compose.yml` file and pass them to the actual environment setting. You could also use `env_file` instead of using `environment` directly.

**Comment by turingking** [comment]
@thasmo Docker-compose does not support this approach。
I wrote a script that helped me complete the setup：
```shell
#!/usr/bin/env bash

# Configure the world resource configuration file. Parameters: target file, world configuration file
handleWorldResources()
{
	filterLineBreaks $2
        overrides="LEVELDATA_OVERRIDES=$filerText"
        grep -q "^LEVELDATA_OVERRIDES=.*" $1 &&
        {
                # If the resource configuration already exists
                replaceText $1 'LEVELDATA_OVERRIDES=' "$overrides"
        } ||
        {
                addText $1 "$overrides"
        }

}

# Configure the mods configuration file. Parameters: target file, mods configuration file
handleModsConfig()
{
	filterLineBreaks $2
	overrides="MODS_OVERRIDES=$filerText"
	grep -q "^MODS_OVERRIDES=.*" $1 &&
        {
                  # If the mods configuration already exists
                replaceText $1 'MODS_OVERRIDES=' "$overrides"
        } ||
        {
                addText $1 "$overrides"
        }

}

# Handle mods. Parameters: target file, mods configuration file
handleMods()
{
	mods=$(cat "$2" >> /dev/null && perl -lane "print $& if /\d{9}/" < "$2")
	mods="MODS=$(echo $mods | sed "s/[ ][ ]*/,/g")"
	grep -q "^MODS=.*" $1 &&
	{
		  # If the mods configuration already exists
		replaceText $1 'MODS=' $mods
	} ||
	{
		addText $1 $mods		
	}
	
	handleModsConfig $1 $2
}


# Remove the text Line breaks
filterLineBreaks()
{
	filerText=$(cat $1 | tr -d '\n')

}




# Replace the text contents. Parameters: target file, replaces the target, replacement
replaceText()
{
	sed -i "s/^$2.*/$3/g" $1	
}


# Add content to the text. Parameters: the target file, add content
addText()
{
	echo "$2" >> $1
}	

handleMods './env/mainworld.env' './mods/mainmods.lua'
handleMods './env/mainsuperworld.env' './mods/mainsupermods.lua'
handleMods './env/caveworld.env' './mods/cavemods.lua'
handleMods './env/cavesuperworld.env' './mods/cavesupermods.lua'


handleWorldResources './env/mainworld.env' './level/mainlevel.lua'
handleWorldResources './env/mainsuperworld.env' './level/mainsuperlevel.lua'
handleWorldResources './env/caveworld.env' './level/cavelevel.lua'
handleWorldResources './env/cavesuperworld.env' './level/cavesuperlevel.lua'

```

**Comment by thasmo** [comment]
Glad you found a way! Nevertheless it should also work by substituting variables in the `docker-compose.yml` file.
