### ISSUE TITLE
Implement a HEALTHCHECK script

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#89]
Write a bash-script and configure it as `HEALTHCHECK` script for the Docker image.

The script should check the container's health against an available DST update and indicate an unhealthy status if the container doesn't run the newest DST version.

See #2 for additional information.

**Comment by meteorlxy** [comment]
HEALTHCHECK is really useful for this kind of docker images.  
BTW, I found that when starting the master server and the cave server together with the same volumes directory (as shown in [example](https://github.com/dst-academy/docker-dontstarvetogether/tree/develop/docs/examples/shard)), the server that get ready first will create the cluster config file first, and the second one will not override it for sure. However, if the cave server get ready first, the server's name shown in the game will be that in the `underworld.env` (also some other configs).  
So maybe the healthcheck script have something to do with this situation?

**Comment by thasmo** [comment]
Hey! `HEALTHCHECK` should not be related to that problem, nor does it help prevent it. #51 is meant to deal with the issue you mentioned, which is a known problem but due to the complexity of how clusters can be set up and configured, it has not yet been fixed completely.

**Comment by thasmo** [comment]
Seems like it's running and showing the health status, but it's not working correctly because containers get `unhealthy` on the first run. Need to check what's wrong.

**Comment by thasmo** [comment]
Double checked it and currently this seems to work as expected. Yay!
