### ISSUE TITLE
Must we preserve previous settings?

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#94]
It's not obvius that if you updates your docker-compose  your server configs are not going to change because we always preserve the previous ones. An example: #86.

Does it have sense? I mean. If I change the mods in my ENV variables the new mods must be installed. That's the same as if I change the maximum players that can play in my server.

I think that we must overwrite this files any time we run the server.

**Comment by thasmo** [comment]
Indeed, that's what #73 is dealing with.

**Comment by BraisGabin** [comment]
Ups! Dupe.
