### ISSUE TITLE
Mods are not being installed on initial boot

### ISSUE THREAD

**Issue by BraisGabin** [yeet-zone/docker-dontstarvetogether#95]
Right now if someone configures his server with mods and run the server using `dst-server start` the mods are never installed. (Use `--update=mods` to workaround this problem).

And if they run `dst-server update --mods` before they run a `dst-server start` the mods are not updated/installed because the file `dedicated_server_mods_setup.lua` is not generated.

**Comment by thasmo** [comment]
Could we check if `MODS` is set and if `$DST_HOME/mods/dedicated_server_mods_setup.lua` is non-existent so we just add `--update=mods`? Would that work? Does that make sense?

**Comment by BraisGabin** [comment]
yes, that would work. But this just show why #67 is a better option. We must create images with the mods in it.
