### ISSUE TITLE
WORLD_PRESET incompatible with leveldataoverride

### ISSUE THREAD

**Issue by thasmo** [yeet-zone/docker-dontstarvetogether#97]
The new `leveldataoverride.lua` file, which is used to configure a world makes things more complicated if someone just want to set a `WORLD_PRESET`. Previously using the `worldgenoverride.lua` it was possible to configure a world-preset like this:
```lua
return {
	override_enabled=true,
	preset="DST_CAVE",
}
```

But now, when using the `leveldataoverride.lua` there are five properties which are required. This is not documented by the way. I found it in the source code. ;)
```lua
return {
	id="DST_CAVE",
	location="cave",
	name="Caves",
	desc="Delve into the caves... together!",
	overrides={},
}
```

This makes it complicated because just setting the environment variable `WORLD_PRESET` when starting the server, won't work anymore. The `id` property obviously defines the actual world preset, but the `location` property may define the actual world settings like `forest` or `cave`.

`name` and `desc` are mandatory but I haven't found out yet whether they're displayed and where. `overrides` are the actual setting-overrides, which are the same as in the old `worldgenoverride.lua`.

---
I think we have two actual choices here.

**Remove WORLD_PRESET**
Simplest option. We just remove the `WORLD_PRESET` environment variable and [related code](https://github.com/dst-academy/docker-dontstarvetogether/blob/develop/build/static/boot/world.sh#L11-L22). This option is easy for us but server maintainers can't easily configure a cave-server. They would have to provide a valid `leveldataoverride.lua` configuration using the `LEVELDATA_OVERRIDES` environment variable.

**Introduce WORLD_LOCATION**
We could add an environment variable `WORLD_LOCATION` which can be set to `forest` or `cave` which will be used when generating the `leveldataoverride.lua` file, besides the `WORLD_PRESET` which will still be used for the `id` property. `name` and `desc` can maybe be empty or we could try using `NAME` and `DESCRIPTION` here too. `overrides` will be empty.

---

Things we should consider:
* Our setup should not get too complicated; it should be kept as simple as possible.
* Server maintainers and devops-engineers should have a way to configure basic settings easily.

Currently when using `WORLD_PRESET` there's an error because the generated `leveldataoverride.lua` is invalid. That's why this issue is part bug and part feature.

**Comment by BraisGabin** [comment]
Great researh! Klei and his documentation...

Ok, does it have sense to have `id=DST_CAVE` with `location=forest`? How much sense?

We probably can keep WORLD_PRESET and autofill `location` with the "normal" value. If someone wants an `id=DST_CAVE, location=forest` he can always use `LEVELDATA_OVERRIDES`.

I think that this is the KISS way. The mantainers that want a server that "just work" can use `WORLD_PRESET`. The ones that want a costumed server can use `LEVELDATA_OVERRIDES`.

**Comment by thasmo** [comment]
I like that idea. I've checked the `id` values, aka `WORLD_PRESET`s and there are two presets -`DST_CAVE` and `DST_CAVE_PLUS` - which need `cave` and the rest needs `forest` by default.

**Comment by thasmo** [comment]
WIP on #99
